{% set name = "gazar" %}
{% set version = "0.0.4" %}
{% set sha256 = "69ac21dd2e3e87252bd2c5d5acdd00b2cee49af993d9436d14df4877940515d9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - affine
    - appdirs
    - gdal
    - mapkit
    - pyproj
    - utm

test:
  imports:
    - gazar
    - gazar.grid
    - gazar.shape
    - gazar.log

about:
  home: https://github.com/snowman2/gazar
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A collection of functions to use with GDAL.'
  description: |
    A collection of functions to use with GDAL. It also
    includes a wrapper for gdal.Dataset with useful methods
    and attributes.
  doc_url: http://gazar.readthedocs.io
  dev_url: https://github.com/snowman2/gazar

extra:
  recipe-maintainers:
    - snowman2
