# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "hHP1e2mqL9uWdW3AL+i1VFvPuAvTzGm0ZZdFspIW9byL6+ap77rGG86DnYXXaGRrfhmGozlQGQgqbw4Ofbtn9GPG29JmXATTeYBW41ehIYOaBmHCvdnQnBWxFPyplKfX5Pl3rZ0pwCKDh36dT9moMe2PGrdi3vR7+Sw7LU11HtXLWrQU0o3rbEae79CqQcw5nkZDHgNHbGmVUcYv1MYAElSiyRLb8Y9vBka5mCYlZ6mWlRupfQTOxdMWtQxRR8MQgkWI8WBsfOPduG6QKo1yvqljbKSEbUzkNh6AVD112xCeWPgyZEKH1daLX3Nu8ZCnLTa1oiMqD0F8WQLHMqtPp+OLbYRFgv5llpJsDpv5/a5t0o4zbxWIGCfti7Ddz0nFQR9Q6eOg4afff4kY44IeRarbS1LJ3ruvknXNrf+61vMg5uEYLUUAzKyhYbl28TWSLmkshHHkh4vK1BLTkrS7WDtx8L8JlfRXHpPBWenrycUx48Vwrdqc+iskx6HT/exBvYZ7v8CtIreDyWxFeOALLfhI0xOmMgax9XEIZcVidXBH4koe8TtMODDAjy9cAELwzkpKic6XORIugRYR10yCLBj54rg4U2fPTwZucYHdq29jGHoIWLmjwfVzRM5zpJXiL2XgCxGo11EtjRw96BS35CENclH/nzcwVDHXQHtrTNk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
