travis:
  secure:
    BINSTAR_TOKEN: kSZY2KKeJodWPRB0E/IerMuazQWKlDMtlRQMw8NoMBg/UXhfchZqFkUwu0sB6dvuzwYfLesnFxnmx10nWzPO1qxOvFKYUUlky+5KwQmqRabBKuCrtI/IMPUdb+KMDCtpWIkkk+Ye+AU9bCSyNMOOlMyR/vaP9/l+bRUBjY5HL01gOhjbMjHbIVExxujqV8DufEUsmCRt9/Bw9QeJGghBb82uxgHgwS2tvHpUKCsJvrFMOnR1SR26+Wn1+cklELUr+o1J+3iNzmeBw9TFLR+YCP7dPFyume8uDj0bm0E0SFcBXXs+eM+Qk4DOIbTfvEOhTqNCdd01vYjCGXHfna+9UMHZ8fOP71KCDoff4SuUIuDK9xq82Nh13TLM9DaBegaqdh0tepc4fC+1L7royiQwcD0OxbnLRvTtVSAWlV5rXvkmcoI1YvgrsMr9gXmc7+zc7irBBLwiMUGUEC2R03BFRRuGUXQLxlJNBdAG+uThfZJ2ZBo6PgoDA+OhNiB0y9w9RcxY23D+zn7C40e+7tVq3LwUfOiS069a96A5a21KulT+wMYrCAEY9UlA7YvMF8esVA4Os4J8pi3YMzhirJTgbX95nNC9CxNrYy2xr7FBWTcQ5L4VViDxCeUpQvooA1niDqIllf0dYSlx7Df9ehbWD9SLorNK+ua6AVmx0lTfbXg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
