travis:
  secure:
    BINSTAR_TOKEN: hHP1e2mqL9uWdW3AL+i1VFvPuAvTzGm0ZZdFspIW9byL6+ap77rGG86DnYXXaGRrfhmGozlQGQgqbw4Ofbtn9GPG29JmXATTeYBW41ehIYOaBmHCvdnQnBWxFPyplKfX5Pl3rZ0pwCKDh36dT9moMe2PGrdi3vR7+Sw7LU11HtXLWrQU0o3rbEae79CqQcw5nkZDHgNHbGmVUcYv1MYAElSiyRLb8Y9vBka5mCYlZ6mWlRupfQTOxdMWtQxRR8MQgkWI8WBsfOPduG6QKo1yvqljbKSEbUzkNh6AVD112xCeWPgyZEKH1daLX3Nu8ZCnLTa1oiMqD0F8WQLHMqtPp+OLbYRFgv5llpJsDpv5/a5t0o4zbxWIGCfti7Ddz0nFQR9Q6eOg4afff4kY44IeRarbS1LJ3ruvknXNrf+61vMg5uEYLUUAzKyhYbl28TWSLmkshHHkh4vK1BLTkrS7WDtx8L8JlfRXHpPBWenrycUx48Vwrdqc+iskx6HT/exBvYZ7v8CtIreDyWxFeOALLfhI0xOmMgax9XEIZcVidXBH4koe8TtMODDAjy9cAELwzkpKic6XORIugRYR10yCLBj54rg4U2fPTwZucYHdq29jGHoIWLmjwfVzRM5zpJXiL2XgCxGo11EtjRw96BS35CENclH/nzcwVDHXQHtrTNk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
